import './globals.css'
import { Montserrat } from 'next/font/google'
import NavBar from '../components/NavBar'

export const runtime = 'edge';

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: "--font-mont"
})

export const metadata = {
  title: 'Natanon Trangratanajit',
  description: 'Generated by Natanon',
}

export default function RootLayout({ children }) {
  return (
    <html className="scroll-smooth" lang="en">
      <body className={`${montserrat.variable} font-mont text-light bg-primary w-full h-min min-h-screen`}>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
